### ISSUE TITLE
DELETE Method in HTTP does not update global list

### ISSUE THREAD

**Issue by mmccool** [thingweb/thingweb-directory#11]
After using DELETE on a previously created TD seems to delete it from the database as the direct URL no longer works.   However, if you ask for ALL the TDs using the /td root URL, the deleted TD is still shown.   This seems to happen only with the HTTP interface (we checked under CoAP and the deleted TDs are NOT listed) so it's probably a caching issue (e.g. the CoAP/HTTP proxy is incorrectly caching the overall TD list).

**Comment by vcharpenay** [comment]
Was fixed in v0.8
