### ISSUE TITLE
TD array convention not applied

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/thingweb-directory#16]
Returned TDs do not follow the array convention, meaning to also wrap single values in an arrays structure, e.g.:
```
"@type": "Property"
```

Maybe we should just drop it as discussed in https://github.com/w3c/wot-thing-description/issues/103 ?

**Comment by vcharpenay** [comment]
Addressed by 52a6821020d15da33cd193efb61efb641e59b3e8. Should however be rediscussed, as you suggest, @mkovatsc.
