### ISSUE TITLE
POST application/sparql-query to /td-lookup/sem

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/thingweb-directory#20]
Writing URI queries is quite tedious. Thus, it would be better, when also a POST (and CoAP FETCH) would be allowed to the semantic look-up resource with a full SPARQL query in the request body.

**Comment by vcharpenay** [comment]
The alternative that was preferred in that case is to access directly the underlying SPARQL endpoint, if an external endpoint is used (preferred case). Clients could then use libraries supporting the well-defined SPARQL protocol.
