### ISSUE TITLE
Returning always URI Path when registering TDs in the system

### ISSUE THREAD

**Issue by onovo1** [thingweb/thingweb-directory#3]
Hi,

The issue is about registering TDs in the ThingWeb directory. Right now, if the TD is already registered, the operation returns a 400 response code. However, the operation does not return the URI path in this case. 
In the particular case that a different node registers the same TD, the node will know that the TD is in the system but it won’t be able to access it (or modified it) since it does not know its URI path.

Thus, I would expect a 400 response code in CoAP with the URI path included. Likewise in HTTP.

Oscar

**Comment by vcharpenay** [comment]
Is fixed by commit 519e616909caf444796330a7a988f570db502721.
