### ISSUE TITLE
After deleting a TD I cannot upload a new TD with the same id

### ISSUE THREAD

**Issue by 6d77** [thingweb/thingweb-directory#38]
After deleting a TD using a HTTP DELETE request, the TD does no longer show up in the query interface. However when I try to upload a new TD with the same ID as the deleted one I get a 204 response, which typically occurs when the id already exists. 

So uploading a new version of a thing using this approach seems not to be possible.

**Comment by karaleina** [comment]
I noticed the same behavior.  I cannot POST new TD with the same ID of the TD that was deleted before.

**Comment by 6d77** [comment]
fixed in master branch with commit 2ac64745dac1e0070bfe55b8d14b19614d205e81
