### ISSUE TITLE
Error in function TDLookUpEPHandler.java

### ISSUE THREAD

**Issue by onovo1** [thingweb/thingweb-directory#5]
Hi guys, 

There is an error in the function named 'get' in the class TDLookUpEPHandler. After finding a TD, the code adds a comma (line 62) after every TD. 
However, in the case where there are no more TDs matching our query, the comma remains there and it is not deleted creating a malformed JSON.
The code should check in line 78, if there is a comma and remove it before adding the closing bracket ('}'). Right now, the code only omit the comma in case the TD is the last one from the list which is just one specific corner case. 

Error in this line:
https://github.com/thingweb/thingweb-directory/blob/8d2a15cdec651e832d5ee43014da46d784144ecf/src/main/java/de/thingweb/directory/handlers/TDLookUpEPHandler.java#L78

Thanks,

Oscar

**Comment by mmccool** [comment]
Interestingly, ES5 does now allow trailing commas in objects and there is a proposal to extend JSON (JSON5) to also allow them.  But for maximum compatibility they should be removed anyway.

**Comment by onovo1** [comment]
That's right. 
Trailing commas are not allowed in JSON as JSON is based on JavaScript's syntax prior to ES5.
Both lines will throw a SyntaxError:

```
JSON.parse('[1, 2, 3, 4, ]');
JSON.parse('{"foo" : 1, }');
```

**Comment by vcharpenay** [comment]
Class not included in new version. Issue is outdated.
