### ISSUE TITLE
Starting command needs to be more specific

### ISSUE THREAD

**Issue by mmccool** [thingweb/thingweb-directory#8]
The startup command as given does not work.  It can't find the JAR file, and even if you are in the same directory as the JAR file (it's hidden down under build/libs) you need a version number.  From the directory where I ran "gradle build", I used the following command to start the server:

    java -jar build/libs/thingweb-directory*.jar `pwd`

**Comment by vcharpenay** [comment]
The distribution has changed, it now comes with a shell script to run. Use `-help` for more details.
